### ISSUE TITLE
Authenticate packet not compatible with 5.1.45-51

### ISSUE THREAD

**Issue by hoisie** [Philio/GoMySQL#11]
We use the mysql server from http://www.percona.com/ . 

Server version: 5.1.45-51-log Percona SQL Server (GPL), XtraDB 10.2

After the Authenticate packet is sent, getResult gets an EOF packet, which implies a malformed auth packet. I'm not familiar with the mysql protocol, so I wouldn't know if there's an easy fix.

**Comment by Philio** [comment]
It works fine with MariaDB, strange that it doesn't work with Percona.
There are 1 or 2 issues with the protocol documentation, but nothing like this.

**Comment by ziutek** [comment]
Try regenerate a password:

```
set password for user@host = password('xxxx');
```

I had a similar problem. It seems that GoMySQL does not work with old MySQL password format.

**Comment by Philio** [comment]
It works only with 4.1+ passwords.

**Comment by Philio** [comment]
This needs testing with the Percona server to see if it is password related or not. I'll do this in a couple of weeks when I'm not travelling around during the xmas holiday, otherwise if someone else (or OP) gets a chance to test, please update.

**Comment by Philio** [comment]
Confirmed issue on Percona server and have a saved image on RS Cloud for further testing, suspect it will be easier to fix with 0.3 so updating target.

**Comment by Philio** [comment]
Percona server reports 4.1 authentication support in the handshake but appears to only work with 4.0 "old" passwords, confirmed with 0.3.0-dev.

I have ticketed Percona regarding this issue

**Comment by Philio** [comment]
Solved in dev branch :)
