### ISSUE TITLE
issue with buffers when compiling

### ISSUE THREAD

**Issue by robear** [Philio/GoMySQL#12]
I got the following errors when compiling with latest versions of Go and GoMySQL:
mysql_packet.go:100: cannot use new([20]uint8) (type *[20]uint8) as type []uint8 in assignment
mysql_packet.go:178: cannot use new([21]uint8) (type *[21]uint8) as type []uint8 in assignment

I am a newb to Go and changed the lines to be:
pkt.scrambleBuff = make([]byte, 20)
pkt.scrambleBuff = make([]byte, 21)

and it compiled, not sure if it is a correct change.

**Comment by SolarGranulation** [comment]
That's the correct change.  Currently found in two forks (including mine) of this project.

There is, I think, another possible solution but that one would require more changes than this approach.

**Comment by wenheping** [comment]
I am wondering why this patch was not committed into trunk ?

**Comment by SolarGranulation** [comment]
I, at least, haven't requested rights to commit to trunk.  I suppose it would be worth considering.

**Comment by robear** [comment]
I support any measure that will help users of the library.

**Comment by Philio** [comment]
I've updated the latest release to resolve this now.
