### ISSUE TITLE
GoMySQL doesn't build with current Go

### ISSUE THREAD

**Issue by dadkins** [Philio/GoMySQL#15]
I applied the followed gofmt transformations

gofmt -r 'log.Stdout -> log.Print' -w `find . -name "*.go"`
gofmt -r 'new([a]byte) -> make([]byte, a)' -w `find . -name "*.go"

and fixed the Makefile in order to build this package.

-include $(GOROOT)/src/Make.$(GOARCH)
+include $(GOROOT)/src/Make.inc

Is this thing still being maintained?

**Comment by Philio** [comment]
I'm going to push an update with these fixes included very soon.

**Comment by Philio** [comment]
Release has been updated. :)
