### ISSUE TITLE
Infinite loop in MySQLStatement.Execute()

### ISSUE THREAD

**Issue by thomaslee** [Philio/GoMySQL#16]
A check on stmt.result.rowsEOF was introduced in 61eeb6aa5... that results in a bug.

If you Execute() a prepared statement that does not return a ResultSet -- e.g. CREATE TABLE, INSERT, etc. -- the for loop in MySQLStatement.getExecuteResult() will never break. This happens because an EOF packet is never received for such queries (a ResultPacketOK is sent by the server instead).

**Comment by Philio** [comment]
Thanks for the report I will patch this right away.

**Comment by Philio** [comment]
Please update to latest release which resolves this issue.
