### ISSUE TITLE
A better $TARG

### ISSUE THREAD

**Issue by thomaslee** [Philio/GoMySQL#17]
A minor one, but for those of us using & developing against goinstall (http://golang.org/cmd/goinstall/), is there any possibility that TARG could be changed from "mysql" to "github.com/Philio/GoMySQL" in the Makefile?

Only a minor niggle, and only one that bothers me when I'm hacking on GoMySQL directly because "make install" installs to src/pkg/mysql instead of src/pkg/github.com/Philio/GoMySQL -- have to remember to copy over to the canonical directory.

See https://github.com/thomaslee/go-dbd-mysql/blob/master/Makefile for an example from a project I'm working on.

**Comment by Philio** [comment]
It doesn't effect installation via goinstall, only if modifying the code?

**Comment by thomaslee** [comment]
That's correct, yup. goinstall installs it to github.com/Philio/GoMySQL.

**Comment by thomaslee** [comment]
Oops. Closed the issue. I'm really not having a great time with github tonight :) Must be tired!

**Comment by Philio** [comment]
I think it would be better just to change the Makefile manually in this instance, otherwise it breaks the ability to download and build normally.

**Comment by cthom06** [comment]
I'd like to second you Philio, I don't really use goinstall, so I don't like when I have to use full URL's to import a package that I installed myself.

**Comment by Philio** [comment]
Same with me, when building I use a shell script which duplicates my local git repo and does make && make install. It's also a bit nicer to use "mysql" over the goinstall long format for the package name.
