### ISSUE TITLE
'if mysql.reader.Buffered() == 0' probably is a bug

### ISSUE THREAD

**Issue by ziutek** [Philio/GoMySQL#26]
Reader.Buffered method in GoMySQL code:

```
$ grep Buffered *.go
mysql.go:                 if mysql.resultSaved && mysql.reader.Buffered() == 0 {
mysql.go:                 if mysql.resultSaved && mysql.reader.Buffered() == 0 {
mysql_statement.go: if mysql.reader.Buffered() == 0 {
mysql_statement.go: if mysql.reader.Buffered() == 0 && stmt.resExecuted {
```

I think it is wrong to rely on if mysql.reader.Buffered() == 0 then there is end of data to read from connection. It is usually true for small replies but with big replies it isn't true.

If you are using buffered io (bufio), you must always to know how many data you need read from a connection and call Reader.Read method as long as you read all needed data from the connection or EOF/error occurs.

**Comment by Philio** [comment]
You are absolutely correct in your observations here. I mentioned on another bug thread that I thing a complete refactor of the packet handling and processing code would be a good idea, this is one of the reasons.

As this library was one of the first things I wrote in the Go languages, I made some mistakes. :-)

I'm thinking about rewriting in such a way that the packet is read fist and processed later. This will resolve most of these kind of issues. A number of people have been very helpful in resolving the current bugs with the library, my aim is to build on this and start working on a new version over the next couple of weeks which will form version 0.3.

**Comment by ziutek** [comment]
I removed 'mysql.reader.Buffered()== 0' from Query() method in my fork:
    --- a/mysql.go
    +++ b/mysql.go
    @@ -200,7 +200,7 @@ func (mysql *MySQL) Query(sql string) (res *MySQLResult, err os.Error) {
                return
            }
            // If result saved and buffer is empty break loop
    -       if mysql.resultSaved && mysql.reader.Buffered() == 0 {
    +       if mysql.resultSaved {
                break
            }
        }

It seems that it is sufficient to check mysql.resultSaved for end of result, but I am not quite sure...

**Comment by Philio** [comment]
I'm going to leave it in for the moment, as it won't hurt to have it.
Will re-evaluate this later on.

**Comment by Philio** [comment]
Added in 0.2.6
