### ISSUE TITLE
about log

### ISSUE THREAD

**Issue by liuaifu** [Philio/GoMySQL#32]
this library is very useful.
can you close the log output by gomysql? or supply a variant to close it.

**Comment by ghost** [comment]
I would suggest changing the mysql.Logging boolean into an instance of the Logger type.
Instead of checking for mysql.Logging == true, just check for mysql.Log != nil every time you want to write to it.

This would at least allow us to hook up our own logger in we found the need to do so.

**Comment by liuaifu** [comment]
before, i didn't known it has Logging, this can solve my problem.

**Comment by ghost** [comment]
The effect is basically the same as the current solution though. If you don't want logging, you just set Logging to false. The downside now is that you can not direct the output to your desired location: like a file.

**Comment by Philio** [comment]
I'll put this as a feature request for 0.3 target, seems like a nice thing to add to the next release.

**Comment by Philio** [comment]
Added to dev branch.
