### ISSUE TITLE
Refactoring of type names

### ISSUE THREAD

**Issue by ghost** [Philio/GoMySQL#33]
Hello Phil,

I was wondering if it is an option to rename the public types in the package to conform a little more with the Go way of doing things.

Specifically: mysql.MySQLServerInfo, mysql.MySQLStatement, etc. Basically all the types that start with MySQL. This causes some unnecessary 'stuttering' when using the package. You always have to specify the package name along with the type when using it, and Go style therefor accepts that you don't need to repeat the package name in the types themselves. I would suggest something like this:

mysql.MySQL -> mysql.Connection
mysql.MySQLServerInfo -> mysql.ServerInfo
mysql.MySQLAuth -> mysql.Auth
mysql.MySQLResult -> mysql.Result
mysql.MySQLField -> mysql.Field
mysql.MySQLFieldFlags -> mysql.FieldFlags
mysql.MySQLRow -> mysql.Row
mysql.MySQLStatement -> mysql.Statement
mysql.MySQLParam -> mysql.Param

I realize that this will break everyone's code so far, but I believe it makes the whole thing that much more elegant and fits with what the rest of the Go package lib looks/behaves like. Since the package is also still in development, I believe this would be the best time do go ahead with a major change like this.

I already tried this in my test branch, and it works without any problems. There are no name  collisions.

**Comment by Philio** [comment]
Sounds like a good idea, the next branch forming 0.3 eventually will be a huge rewrite, so it would make sense to do this for this version and leave 0.2 as it is for now. I think the 0.2 branch is now pretty solid (thanks to several contributors) so I'll flag this for inclusion in 0.3.

**Comment by Philio** [comment]
Soved in dev branch, beta coming soon.
