### ISSUE TITLE
Parsing of EOF packet not backward compatible

### ISSUE THREAD

**Issue by piotrnar** [Philio/GoMySQL#39]
I wasn't able to use the package with mysql 4.1.25.
After some time I figured out what was wrong.

In file mysql_packet.go there should be:

/**
- Read the EOF packet from the buffer
  */
  func (pkt *packetEOF) read(reader *bufio.Reader) (err os.Error) {
  // Read field count
  c, err := reader.ReadByte()
  if err != nil {
      return
  }
  pkt.fieldCount = uint8(c)
  if pkt.header.length == 1 {
      pkt.warningCount = 0
      pkt.serverStatus = 0x200
      return
  }
  // Read warning count
      ...

**Comment by Philio** [comment]
Thanks for the report, this is something that will be addressed in the next major release (current dev branch) however it's still a while off completion. The library will fully support the 4.1+ protocol and the pre-4.1 protocol with the next release.

Your edit is correct for pre-4.1 protocol specs, however I'm surprised that you should need this as you're using 4.1.

More info here:

http://forge.mysql.com/wiki/MySQL_Internals_ClientServer_Protocol#EOF_Packet

We have a google group to discuss development, if it's of any interest please check it out: https://groups.google.com/group/gomysql

**Comment by piotrnar** [comment]
Thanks for making the library - it works pretty great.
Except that thing it seems to be working quite well with my mysql.
But it took me awhile to find the problem, because this function was assuming the longer message, reading too many bytes from the socket, and then all the further communication was going out of sync.
I also don't know why this message has no payload in my case, but a check for a sufficient value in kt.header.length, in the function, seems to be reasonable, even before the major release.

**Comment by Philio** [comment]
It's a bit of a weird one this, as version 0.2 has a minimum requirement of 4.1 and no support for pre-4.1 style packets. However despite the fact that you are using a 4.1+ server, according to MySQL's documentation, your server is sending an incorrect packet.

You're right it's an easy fix, but I'd like to get to the bottom of why this occurs rather than patch something that apparently shouldn't happen.

I would bug this with MySQL, but I honestly don't think they would take a second glance as 4.1 is really quite obsolete these days. I'm not even sure if they support 5.0 any more?

Just out of curiosity, why have you not upgraded to a more recent release?

**Comment by piotrnar** [comment]
I see you point, but I cannot let you on my server.

I use quite standard freebsd and I didn't do any magic to install it.
Though I admit that I upgraded it many times since the beginning.
Maybe even downgraded. :)
I actually found v4 much faster for my application than v5. 

Anyway, when I select version() it prints "4.1.25"

**Comment by Philio** [comment]
That's ok I wasn't suggesting you let me use your server! :)

To test an OS/server combination I don't run myself I usually use cloud server nodes as I can image/save/destroy/recreate as I please for testing.

Which version of FreeBSD are you using? Also the actual package you have installed would be helpful (or compiler options if a source build)?

**Comment by piotrnar** [comment]
Well, letting you onto the server wouldn't be unreasonable. If only possible.. :)

To reproduce it you need:
1) A minimal version of FreeBSD 7.3-RELEASE installed on a virtual machine
2) pkg_add -r mysql41-server
3) start the server (I had to reboot)
4) any query (i.e. "SHOW DATABASES") should give you an empty EOF packet already

**Comment by Philio** [comment]
Thanks for this, I'll try this as soon as I get the chance!

**Comment by Philio** [comment]
This issue is resolved in the dev branch. Some sort of beta release will be available soon.
