### ISSUE TITLE
SELECT numerous columns issue.

### ISSUE THREAD

**Issue by yunge** [Philio/GoMySQL#48]
When I SELECT data from a table which has numerous columns, it would return an empty Resultset, if I delete some columns( just some 'int' columns), then it worked.

The output shows it stopped after "Received row packet":

2011/03/01 10:13:58 Reading result packet from server
2011/03/01 10:13:58 [54] Received field packet
2011/03/01 10:13:58 Reading result packet from server
2011/03/01 10:13:58 [55] Received field packet
2011/03/01 10:13:58 Reading result packet from server
2011/03/01 10:13:58 [56] Received EOF packet
2011/03/01 10:13:58 === Server Status ===
2011/03/01 10:13:58 In transaction: 0
2011/03/01 10:13:58 Auto commit enabled: 1
2011/03/01 10:13:58 More results exist: 0
2011/03/01 10:13:58 No good indexes were used: 0
2011/03/01 10:13:58 No indexes were used: 1
2011/03/01 10:13:58 Cursor exists: 0
2011/03/01 10:13:58 Last row has been sent: 0
2011/03/01 10:13:58 Database dropped: 0
2011/03/01 10:13:58 No backslash escapes: 0
2011/03/01 10:13:58 Metadata has changed: 0
2011/03/01 10:13:58 === Begin store result ===
2011/03/01 10:13:58 Reading result packet from server
2011/03/01 10:13:58 [57] Received row packet
Execute RowCount:0  sql: SELECT `Water`,`Arg`,
//The last line was output from my own code.

**Comment by Philio** [comment]
Hi,

Could you please provide me with the table structure you're using and which version of MySQL?

One of the tests I run uses a table with every possible type of field supported by MySQL, which runs without issue on multiple versions of MySQL so it's strange you're having problems with int fields.

It might also he helpful to include the code you're using.

**Comment by yunge** [comment]
Hi Philio,

I send the sql file and the code to phil@bayfmail.com, pls check it, thanks.

**Comment by Philio** [comment]
Thanks for sending that, I'll look into this ASAP.

**Comment by Philio** [comment]
I've found a couple of issues:
1. There is an error response from strconv which is not retained properly.
2. There is no NULL check in the row handler.

I've fixed the second one and have your code working perfectly locally. I'll sort out the first bit and commit a new release.

**Comment by Philio** [comment]
Resolved in 0.3-RC2

**Comment by yunge** [comment]
It's works fine, thanks!
