### ISSUE TITLE
Received unknown packet from server

### ISSUE THREAD

**Issue by garysims** [Philio/GoMySQL#5]
In my test of my ESMTP server (http://code.google.com/p/goesmtp), I came across an odd error when trying to get the MAX() on an empty table. The resulting debug shows that GoMySQL receives an unknown packet from the server!

Here is the debug output:

```
2010/05/31 17:35:10 Connect called
2010/05/31 17:35:10 Connected using TCP/IP
2010/05/31 17:35:11 [0] Received init packet from server
2010/05/31 17:35:11 [1] Sent auth packet to server
2010/05/31 17:35:11 [2] Received ok packet from server
2010/05/31 17:35:11 Current result set saved
2010/05/31 17:35:11 Query called with SQL: CREATE TABLE IF NOT EXISTS `bugtest` (id int not NULL)
2010/05/31 17:35:11 [0] Sent query command to server
2010/05/31 17:35:11 [1] Received ok packet from server
2010/05/31 17:35:11 Current result set saved
2010/05/31 17:35:11 Query called with SQL: SELECT max(id) FROM bugtest
2010/05/31 17:35:11 [0] Sent query command to server
2010/05/31 17:35:11 [1] Received result set packet from server
2010/05/31 17:35:11 [2] Received field packet from server
2010/05/31 17:35:11 [3] Received eof packet from server
2010/05/31 17:35:11 End of field packets
2010/05/31 17:35:11 [4] Received unknown packet from server
Error 0 
```

Here is a test program which demonstrates this problem:

```
package main

import (
    "mysql"
    "fmt"
    "os"
)

func main() {
    // Create new instance
    db := mysql.New()
    // Enable logging
    db.Logging = true
    // Connect to database
    db.Connect("localhost", "user", "password", "gotesting")
    if db.Errno != 0 {
        fmt.Printf("Error #%d %s\n", db.Errno, db.Error)
        os.Exit(1)
    }

    // Create TABLE
    _, errc := db.Query("CREATE TABLE IF NOT EXISTS `bugtest` (id int not NULL)")
    if errc != nil {
        fmt.Printf("Error #%d %s\n", db.Errno, db.Error)
    }


    // Query database
    res, err := db.Query("SELECT max(id) FROM bugtest")
    if err != nil {
        fmt.Printf("Error #%d %s\n", db.Errno, db.Error)
        os.Exit(1)
    }
    // Display results
    var row map[string]interface{}
    for {
        row = res.FetchMap()
        if row == nil {
            break
        }
        for key, value := range row {
            fmt.Printf("%s:%v\n", key, value)
        }
    }
    // Close connection
    db.Close()
}
```

**Comment by Philio** [comment]
Hi Gary,

Thanks for the report and once again great explanation.

This isn't something I've come accross before but will run this code later and see what happens.

Cheers,
Phil.

**Comment by Philio** [comment]
Hi Gary,

I've verified the bug, looking into possible causes and solutions.

Phil.

**Comment by Philio** [comment]
This is a bit strange, MySQL is sending a NULL

$ ./8.out 
2010/06/07 23:08:26 Connect called
2010/06/07 23:08:26 Connected using unix socket
2010/06/07 23:08:26 [0] Received init packet from server
2010/06/07 23:08:26 [1] Sent auth packet to server
2010/06/07 23:08:26 [2] Received ok packet from server
2010/06/07 23:08:26 Current result set saved
2010/06/07 23:08:26 Query called with SQL: CREATE TABLE IF NOT EXISTS `bugtest` (id int not NULL)
2010/06/07 23:08:26 [0] Sent query command to server
2010/06/07 23:08:26 [1] Received ok packet from server
2010/06/07 23:08:26 Current result set saved
2010/06/07 23:08:26 Query called with SQL: SELECT max(id) FROM bugtest
2010/06/07 23:08:26 [0] Sent query command to server
2010/06/07 23:08:26 [1] Received result set packet from server
2010/06/07 23:08:26 [2] Received field packet from server
2010/06/07 23:08:26 [3] Received eof packet from server
2010/06/07 23:08:26 End of field packets
2010/06/07 23:08:26 [4] Received unknown packet from server beginning with 251 length 1
2010/06/07 23:08:26 [5] Received eof packet from server
2010/06/07 23:08:26 End of row data packets
2010/06/07 23:08:26 Current result set saved
2010/06/07 23:08:26 Close called
2010/06/07 23:08:26 [0] Sent quit command to server
2010/06/07 23:08:26 Closed connection to server

This is not in the protocol spec!!!

**Comment by Philio** [comment]
A fix for this bug has been committed to the master branch.

2010/06/08 00:05:22 Connect called
2010/06/08 00:05:22 Connected using unix socket
2010/06/08 00:05:22 [0] Received init packet from server
2010/06/08 00:05:22 [1] Sent auth packet to server
2010/06/08 00:05:22 [2] Received ok packet from server
2010/06/08 00:05:22 Current result set saved
2010/06/08 00:05:22 Query called with SQL: CREATE TABLE IF NOT EXISTS `bugtest` (id int not NULL)
2010/06/08 00:05:22 [0] Sent query command to server
2010/06/08 00:05:22 [1] Received ok packet from server
2010/06/08 00:05:22 Current result set saved
2010/06/08 00:05:22 Query called with SQL: SELECT max(id) FROM bugtest
2010/06/08 00:05:22 [0] Sent query command to server
2010/06/08 00:05:22 [1] Received result set packet from server
2010/06/08 00:05:22 [2] Received field packet from server
2010/06/08 00:05:22 [3] Received eof packet from server
2010/06/08 00:05:22 End of field packets
2010/06/08 00:05:22 [4] Received row data packet from server
2010/06/08 00:05:22 [5] Received eof packet from server
2010/06/08 00:05:22 End of row data packets
2010/06/08 00:05:22 Current result set saved
max(id):0
2010/06/08 00:05:22 Close called
2010/06/08 00:05:22 [0] Sent quit command to server
2010/06/08 00:05:22 Closed connection to server
