### ISSUE TITLE
interface conversion error INT -> int32

### ISSUE THREAD

**Issue by MrDark** [Philio/GoMySQL#50]
When I try to fetch an INT value from the database and convert it using the interface{} to Go int32 I get the following runtime error.

panic: interface conversion: interface is int64, not int

This is what I try to do:
value := row["someColumn"].(int32)

Judging from the conversion table in the README.markdown database INT types will be converted to the Go datatype int32. When I try row["someColumn"].(int) it fails with the same error.

**Comment by Philio** [comment]
Hi there,

As all integer values are sent as strings by MySQL for queries, for ease of use they are converted to either uint64 or int64, depending on if the unsigned flag is set for the field.

The code that does this can be found here: https://github.com/Philio/GoMySQL/blob/master/handler.go#L135

Hence if you have signed ints:

value := row["someColumn"].(int64)

Or unsigned ints:

value := row["someColumn"].(uint64)

Should work without issue.

You can find out if int columns are signed or unsigned programmatically by looking at the field structs.

**Comment by Philio** [comment]
Also should add that the conversion table only applies to prepared statements and as mentioned it's not that relevant to the 0.3 client as conversion is provided for you via BindResult and Fetch in statements.
