### ISSUE TITLE
Can't connect to MySQL at 127.0.0.1 using TCP

### ISSUE THREAD

**Issue by ziutek** [Philio/GoMySQL#9]
When mysql.auth.host is "127.0.0.1" mysql.connect try establish connection via unix domain socket. It prevents intentionally connect to localhost via TCP. I think there will be enough to use unix socket when mysql.auth.host is "localhost". This allow connect to 127.0.0.1 from chroot environment, where MySQL unix socket is inaccessible.

**Comment by Philio** [comment]
Probably a good idea to be able to force to connect 1 way or the other. Initially I just wanted to keep the required parameters to a bare minimum.

I'll push something into the next release to this extent.

**Comment by ziutek** [comment]
It requires very simple modification and no additional parameters. It's enough to change one line in mysql.go:
    -- if mysql.auth.host == "localhost" || mysql.auth.host == "127.0.0.1" {
    ++ if mysql.auth.host == "localhost" {

**Comment by Philio** [comment]
This feature is implemented in the dev branch, beta coming soon.
